package synth

import (
	"bufio"
	"encoding/csv"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/Sanjith-Shan/RiskGate/internal/data"
)

// Columns written to the transaction file: the IEEE-CIS names of every
// column RiskGate reads, plus the label. The real file has about 394
// columns; the loader selects by name, so the others need not exist here.
var txnHeader = []string{
	data.ColTransactionID, data.ColIsFraud, data.ColTransactionDT, data.ColTransactionAmt,
	data.ColProductCD, data.ColCard1, data.ColCard4, data.ColCard6, data.ColAddr1,
	data.ColAddr2, data.ColDist1, data.ColPEmail, data.ColREmail, data.ColD1,
}

// markerText is written to the SYNTHETIC marker file.
const markerText = `SYNTHETIC DATA. Generated by cmd/synth, not IEEE-CIS.
Nothing computed from these files is a result. Every tool that reads them
labels its output SYNTHETIC. Run scripts/fetch_data.sh for the real data.
`

// WriteCSV writes train_transaction.csv, train_identity.csv, and the
// SYNTHETIC marker into dir. Numbers use the shortest decimal that parses
// back to the same float64, and missing values are empty cells, as in the
// Kaggle files.
func WriteCSV(dir string, txns []data.Txn) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, data.SyntheticMarker), []byte(markerText), 0o644); err != nil {
		return err
	}
	if err := writeFile(filepath.Join(dir, "train_transaction.csv"), func(w *bufio.Writer) error {
		w.WriteString(strings.Join(txnHeader, ",") + "\n")
		var b []byte
		for i := range txns {
			t := &txns[i]
			b = b[:0]
			b = strconv.AppendInt(b, t.ID, 10)
			b = append(b, ',')
			b = strconv.AppendInt(b, int64(t.IsFraud), 10)
			b = append(b, ',')
			b = strconv.AppendInt(b, t.DT, 10)
			for _, f := range []any{t.Amount, t.ProductCode, t.Card1, t.Card4, t.Card6, t.Addr1,
				t.Addr2, t.Dist1, t.PEmail, t.REmail, t.D1} {
				b = append(b, ',')
				switch v := f.(type) {
				case float64:
					if !math.IsNaN(v) {
						b = strconv.AppendFloat(b, v, 'f', -1, 64)
					}
				case string:
					if strings.ContainsAny(v, ",\"\n\r") {
						return fmt.Errorf("synth: value %q needs CSV quoting", v)
					}
					b = append(b, v...)
				}
			}
			b = append(b, '\n')
			if _, err := w.Write(b); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return err
	}
	return writeFile(filepath.Join(dir, "train_identity.csv"), func(w *bufio.Writer) error {
		cw := csv.NewWriter(w)
		cw.Write([]string{data.ColTransactionID, data.ColDeviceType, data.ColDeviceInfo})
		for i := range txns {
			t := &txns[i]
			if t.DeviceType == "" && t.DeviceInfo == "" {
				continue
			}
			cw.Write([]string{strconv.FormatInt(t.ID, 10), t.DeviceType, t.DeviceInfo})
		}
		cw.Flush()
		return cw.Error()
	})
}

func writeFile(path string, fill func(*bufio.Writer) error) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	w := bufio.NewWriterSize(f, 1<<20)
	if err := fill(w); err != nil {
		f.Close()
		return err
	}
	if err := w.Flush(); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}
