// Command synth writes a SYNTHETIC dataset in the IEEE-CIS file format, so
// the loader, feature engine, export, and everything downstream can run
// before the real data is downloaded. Nothing computed from it is a result.
//
//	go run ./cmd/synth                 # 590,540 rows into data/synth
//	go run ./cmd/synth -rows 20000 -out /tmp/small
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"time"

	"github.com/Sanjith-Shan/RiskGate/internal/data/synth"
)

const banner = "*** SYNTHETIC DATA: generated by cmd/synth, not IEEE-CIS. Not a result. ***"

func main() {
	log.SetFlags(0)
	var cfg synth.Config
	out := flag.String("out", "data/synth", "output directory")
	flag.IntVar(&cfg.Rows, "rows", 590540, "transactions to generate")
	flag.IntVar(&cfg.Days, "days", 182, "days spanned")
	flag.Float64Var(&cfg.FraudRate, "fraud-rate", 0.035, "target fraud share")
	flag.IntVar(&cfg.Customers, "customers", 0, "legitimate customers (0: rows/5)")
	flag.Uint64Var(&cfg.Seed, "seed", 1, "random seed; the same seed gives the same files")
	flag.Parse()

	fmt.Fprintln(os.Stderr, banner)
	start := time.Now()
	txns, s := synth.Generate(cfg)
	gen := time.Since(start)
	if err := synth.WriteCSV(*out, txns); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("SYNTHETIC: wrote %d rows to %s in %v (generate %v)\n",
		s.Rows, *out, time.Since(start).Round(time.Millisecond), gen.Round(time.Millisecond))
	fmt.Printf("SYNTHETIC: fraud %d (%.2f%%), with identity %.1f%%, TransactionDT %d..%d\n",
		s.Fraud, 100*float64(s.Fraud)/float64(s.Rows), 100*float64(s.WithIdentity)/float64(s.Rows), s.FirstDT, s.LastDT)
	patterns := make([]string, 0, len(s.ByPattern))
	for p := range s.ByPattern {
		patterns = append(patterns, p)
	}
	sort.Strings(patterns)
	for _, p := range patterns {
		fmt.Printf("SYNTHETIC:   %-17s %d\n", p, s.ByPattern[p])
	}
	fmt.Fprintln(os.Stderr, banner)
}
